### ISSUE TITLE
Configurable `delayBetweenMeasurementsmS`

### ISSUE THREAD

**Issue by imposibrus** [wirenboard/wb-mqtt-adc#18]
Here on line 105 a hard-coded delay "10 ms":
https://github.com/wirenboard/wb-homa-adc/blob/71a2227fb061ea7d79e0da7b467c41f9c2e4d190/src/adc_driver.cpp#L100-L108

Would be great if user can could configure this value through the config file🙂

**Comment by cu6apum** [comment]
Patch done, uploaded to the crew (can't make a branch here). Cheerz.

**Comment by webconn** [comment]
Fixed by adding `poll_interval` in 2.1.0 (#23)
